version: '3.8'

services:
  db:
    image: mariadb:latest  # Wechsel von MySQL zu MariaDB
    container_name: my_xampp_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: essenausgabe
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
      MARIADB_INNODB_FORCE_RECOVERY: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_java_app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/essenausgabe  # MariaDB-Treiber verwenden
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect  # MariaDB Dialekt setzen

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_react_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./frontend:/app

volumes:
  db_data:
